### ISSUE TITLE
ReDesign

### ISSUE THREAD

**Issue by azu** [proofdict/proofdict#51]
1 dictionary per 1 file limits portability.
This limitation comes from maintaincebility.

But, I think that maintaince can be possible even if one dictionary includes multiple items.
prh has not `id` like midashi-見出し.

We can introduce midashi for each item.
The format is almost same to currenct. It is just multiple items.

```yaml
# `id` is unique string
-   id: ECMASCript
    # `description` is a short comment
    description: 'Reference https://www.ecma-international.org/publications/standards/Ecma-262.htm'
    # `expected` is expected result
    # `$1` ... `$9` reference `patterns`'s capture word
    # This is same behavior with RegExp https://github.com/zeeshanu/learn-regex 
    expected: ECMAScript $1
    # `patterns` are match string or RegExp
    # RegExp should be started with `/` and be ended with `/`
    # Also, can use `()` for capturing
    patterns:
      - /ECMAScript([0-9]+)/i
      - /ECMA Script([0-9]+)/i
    # `allows` define ignore patterns
    #  If `allows` pattern are matched, just ignore it
    allows:
      - ECMASCRIPT1
    # `specs` are test cases
    # `specs[n].from` is actual word
    # `specs[n].to` is expected word that is replaced result
    specs:
      - from: ECMASCRIPT5
        to: ECMAScript 5
      - from: ECMASCRIPT1
        to: ECMASCRIPT1 # because "ECMASCRIPT1" is allowed
    # `tags` are keywords
    # Some `tag` means special meaning
    tags:
      - noun
      - JavaScript

-   id: jQuery
    expected: jQuery
    patterns:
      - /jquery/i
    specs:
      - from: jquery
        to: jQuery
```

This ways's pros is easy to use.
Also, we can sort dictionary.

Per file approach has file name problem #44 .
This approach resolve it.
