### ISSUE TITLE
Captalize

### ISSUE THREAD

**Issue by azu** [proofdict/proofdict#57]
I do not want to `$1` in dictionary.

```yaml
id: 01F0W5YS57VWFW3DAP3EC92D6Z
description: 'https://github.com/sveltejs'
expected: $1velte
patterns:
  - /(s)velete/i
allows: []
specs:
  - from: svelete
    to: svelte
  - from: Svelete
    to: Svelte
tags:
  - noun
```

Instead of it, I want to write the following:

```yaml

id: 01F0W5YS57VWFW3DAP3EC92D6Z
description: 'https://github.com/sveltejs'
expected: Svelte
patterns:
  - /svelete/i
allows: []
capitalize: true
specs:
  - from: svelete
    to: svelte
  - from: Svelete
    to: Svelte
tags:
  - noun
```
